# configs/augmentation_configs/basic_augmentation.yaml
augmentation:
  use_augmentation: true
  transforms:
    - name: SomeOf
      params:
        p: 0.5
        n: 1
        transforms:
          - name: RandomResizedCrop
            params:
              height: 512
              width: 512
              scale: [0.5, 1.0]
              p: 0.5
          - name: Resize
            params:
              height: 512
              width: 512
              p: 0.5
    - name: RandomBrightnessContrast
      params:
        p: 0.2
    - name: HorizontalFlip
      params:
        p: 0.5

